### ISSUE TITLE
Many Bugs in End Game

### ISSUE THREAD

**Issue by weebmxz** [hocha113/CalamityOverhaul#6]
After defeating the first Boss Rush and placing the Omega substance Polymerizer the whole world kind of went downhill. Many Blocks started to be placed sideways and things like the Magic Storage didn't work. There were issues with taking stuff out, putting stuff in or crafting items. Also probelms with other players in the world started to emerge. My friend was invisible with infinite scaling HP or just in general laggy movement. No other big mods were activated only Calamity Vanities and Fargos and QoL mods were active. Really sad because we were very keen on crafting those Endgame Weapons.

Hope it gets fixed soon

**Comment by hocha113** [comment]
This issue does occur in multiplayer mode, and I am certain it is related to the Magic Storage mod. If you disable the Magic Storage mod, it should work fine in multiplayer. Therefore, the fix for this issue involves addressing the interaction with third-party mods. I will try to resolve it, and this issue should be fixed in the next update, version 0.4.

**Comment by Satyrrrr** [comment]
im still having an issue where the polymerizer is still making the magic storage not letting me craft or take any items out of it in multiplayer

**Comment by hocha113** [comment]
Should have been solved now, the problem and https://github.com/hocha113/CalamityOverhaul/issues/20 should be a reason, they have been together to repair
